src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=4096, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $year;

    /**
     * @ORM\Column(type="integer")
     */
    private $duration;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_added;

    /**
     * @ORM\Column(type="integer")
     */
    private $views;

    /**
     * @ORM\Column(type="boolean")
     */
    private $alert;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Category", inversedBy="movies")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    public function __construct()
    {
        $this->category = new ArrayCollection();
    }
    
    public function getDurationString(): ?string
    {
        $h = (int)($this->duration / 60);
        $m = ($this->duration % 60);
        
        return ($h > 0 ? $h."h " : "").($m > 0 ? ($m > 10 ? $m."m" : "0".$m."m") : "");
    }
    
    public function getCategoriesString(): ?string
    {
        return implode(', ', array_map(function($c) {
            return $c->getName();
        }, iterator_to_array($this->getCategory())));
    }
    
    public function getDescriptionShort(): ?string
    {
        return (strlen($this->description) > 200 ? substr($this->description, 0, 200)."..." : $this->description);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDateAdded(): ?\DateTimeInterface
    {
        return $this->date_added;
    }

    public function setDateAdded(\DateTimeInterface $date_added): self
    {
        $this->date_added = $date_added;

        return $this;
    }

    public function getViews(): ?int
    {
        return $this->views;
    }

    public function setViews(int $views): self
    {
        $this->views = $views;

        return $this;
    }

    public function getAlert(): ?bool
    {
        return $this->alert;
    }

    public function setAlert(bool $alert): self
    {
        $this->alert = $alert;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->category->contains($category)) {
            $this->category[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->category->contains($category)) {
            $this->category->removeElement($category);
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }
}

templates/movies/_category.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}{{ category.name }}{% endblock %}

{% block page_contents %}
    <h1>{{ category.name }}</h1>
    <div class="group">
        {% for movie in movies %}
            <a class="item" rel="popover" data-title="{{ movie.name }}" data-content="{{ movie.descriptionShort }}" href="{{ path('app_movie', {'id': movie.id}) }}">
                <div class="image">
                    <img src="{{ path('app_movie_image', {'id': movie.id}) }}" />
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/movies/_movie.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}{{ movie.name }}{% endblock %}

{% block page_contents %}
    <div class="background">
        <img src="{{ path('app_movie_image', {'id': movie.id}) }}" />
        <div class="layer"></div>
        <div class="layer2"></div>
    </div>
    <div class="movie">
        <video width="100%" height="100%" controls>
            <source src="{{ path('app_movie_video', {'id': movie.id}) }}" type="video/mp4">
            Your browser does not support the video tag.
            </video>
        <div class="title">{{ movie.name }}</div>
        <div class="info">{{ movie.year }} • {{ movie.durationString }} • {% for category in movie.category %}<a href="{{ path('app_categories', {"id": category.id}) }}">{{ category.name }}</a> • {% endfor %}</div>
        <div class="description">{{ movie.description }}</div>
    </div>
{% endblock %}

templates/movies/_movies.html.twig
{% extends 'layout/layout.html.twig' %}

{% block title %}{% trans %}MOVIES{% endtrans %}{% endblock %}

{% block page_contents %}
    <div class="group">
        {% for movie in movies %}
            <a class="item" rel="popover" data-title="{{ movie.name }}" data-content="{{ movie.descriptionShort }}" href="{{ path('app_movie', {'id': movie.id}) }}">
                <div class="image">
                    <img src="{{ path('app_movie_image', {'id': movie.id}) }}" />
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

templates/movies/_movies_ajax.html.twig
<div class="stick">
    {% for movie in movies %}
        <a class="item" rel="popover" data-title="{{ movie.name }}" data-content="{{ movie.descriptionShort }}"  href="{{ path('app_movie', {'id': movie.id}) }}">
            <div class="image">
                <img src="{{ path('app_movie_image', {'id': movie.id}) }}" />
            </div>
        </a>
    {% endfor %}
</div>
<script>
    $('.stick').each(function () {
        if ($(this).data('stick') === undefined) {
            $(this).data('stick', true);
            $(this).slick({
                dots: false,
                infinite: false,
                speed: 300,
                slidesToShow: 5,
                slidesToScroll: 1,
                responsive: [
                    {
                      breakpoint: 1024,
                      settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3,
                        infinite: true,
                        dots: true
                      }
                    },
                    {
                      breakpoint: 600,
                      settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                      }
                    },
                    {
                      breakpoint: 480,
                      settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1
                      }
                    }
                ]
            });
        }
    });
    $('*[rel=popover]').popover({
        'trigger': 'hover'
    });
</script>